export const featuresData = [
  {
    id: 1,
    bgColor: "bg-[#DCEFFF]/70",
    title: "Goodbye to writer's block: Ready-to-use prompts for any content",
    number: "01",
    description: "An AI marketing and sales application uses artificial intelligence to enhance and automate marketing and sales processes, improving customer engagement and driving conversions.",
    listItems: [
      "Predictive analytics",
      "Personalized customer interactions",
      "Automated lead scoring and management",
      "Chatbot and virtual assistants",
    ],
    imageUrl: "/assets/marketing-apps.png",
  },
  {
    id: 2,
    bgColor: "bg-[#F9DE6F]/30",
    title: "Text to videos and Product AI",
    number: "02",
    description: "The Imaginate application converts text into videos, utilizing advanced AI to generate engaging multimedia content from written input.",
    listItems: [
      "Text-to-video conversion",
      "Customizable templates",
      "Voiceover integration",
      "Multilingual support",
    ],
    imageUrl: "/assets/text-to-video.png",
  },
  {
    id: 3,
    bgColor: "bg-[#9AEEE7]/30",
    title: "Marketing and sales assistants",
    number: "03",
    description: "Marketing and sales assistants are AI-powered tools designed to support and enhance your marketing and sales efforts, improving efficiency and customer engagement.",
    listItems: [
      "Automated email campaigns",
      "Sales pipeline management",
      "Customer interaction tracking",
      "Performance analytics",
    ],
    imageUrl: "/assets/marketing-assistants.png",
  },
  {
    id: 4,
    bgColor: "bg-[#FAE8F1]/30",
    title: "AI-powered assistants that understand you",
    number: "04",
    description: "An AI-powered tool for creating optimized landing pages and emails, designed to enhance user engagement and conversion rates through intelligent design and content suggestions.",
    listItems: [
      "Smart template library",
      "AI-Driven content generation",
      "Real-Time analytics and optimization",
      "Integration with marketing tools",
    ],
    imageUrl: "/assets/ai-assistants.png",
  },
  {
    id: 5,
    bgColor: "bg-[#FFEDE6]/30",
    title: "No-code power: Tailored apps for any task",
    number: "05",
    description: "Build custom apps with easy-to-use components to design exactly what you need for each use case. By training these apps with your best examples, you'll get high-quality results that are consistent and repeatable every time – no need for complex prompt engineering.",
    listItems: [
      "Dynamic audience segmentation",
      "Conversational AI chatbots",
      "Predictive campaign analytics",
      "Seamless integration with marketing platforms",
    ],
    imageUrl: "/assets/custom-gpts.png",
  },
  {
    id: 6,
    bgColor: "bg-[#E2F0CB]/30",
    title: "Social planner hub",
    number: "06",
    description: "The Social Planner Hub streamlines social media management with a Conversation Hub, Analytics, and Scheduler for effective planning and execution.",
    listItems: [
      "Social media conversation hub",
      "Scheduler page plan and schedule social media posts",
      "Content calendar and collaboration",
      "Social media analytics",
    ],
    imageUrl: "/assets/social-planner.png",
  },
];
