export const features = [
  {
    id: 1,
    title: "AI",
    icon: "Group 11.svg",
    top: 50,
    left: 50,
    shadowColor: "voilet",
  },
  {
    id: 17,
    title: "AI",
    icon: "Group 17.svg",
    top: 150,
    left: 220,
    shadowColor: "voilet",
  },
  {
    id: 2,
    title: "AI",
    icon: "Group 15.svg",
    top: 250,
    left: 50,
    shadowColor: "voilet",
  },
  {
    id: 3,
    title: "AI",
    icon: "Group 5.svg",
    top: 350,
    left: 220,
    shadowColor: "voilet",
  },
  {
    id: 4,
    title: "AI",
    icon: "Group 8.svg",
    top: 450,
    left: 50,
    shadowColor: "voilet",
  },
  {
    id: 10,
    title: "AI",
    icon: "Group 7.svg",
    top: 600,
    left: 300,
    shadowColor: "voilet",
  },
  {
    id: 5,
    title: "AI",
    icon: "Group 10.svg",
    top: 650,
    left: 750,
    shadowColor: "voilet",
  },
  {
    id: 7,
    title: "AI",
    icon: "Group 12.svg",
    top: 580,
    left: 970,
    shadowColor: "voilet",
  },
  {
    id: 8,
    title: "AI",
    icon: "Group 13.svg",
    top: 440,
    left: 1150,
    shadowColor: "voilet",
    anchor: "bottom",
  },
  {
    id: 6,
    title: "AI",
    icon: "Group 9.svg",
    top: 100,
    left: 1150,
    shadowColor: "voilet",
    anchor: "bottom",
  },


  {
    id: 11,
    title: "AI",
    icon: "Group 2.svg",
    top: 300,
    left: 1020,
    shadowColor: "voilet",
    anchor: "bottom",
  },
  {
    id: 9,
    title: "AI",
    icon: "Group 14.svg",
    top: 580,
    left: 500,
    shadowColor: "voilet",
  },
];

