import Motion from "@/components/Motion";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Switch } from "@/components/ui/switch";
import { Fragment } from "react";
import { timezones } from "../constants/timezones";

export default function GeneralSection() {
  return (
    <Fragment>
      <Motion transition={{ duration: 0.2 }} variants={{ hidden: { opacity: 0 }, visible: { opacity: 1 } }}>
        <div className="flex gap-5">
          <div className="w-full space-y-12">
            <div className="flex items-center">
              <label htmlFor="status" className="flex items-center gap-1 w-1/5 min-w-[300px] font-medium">
                Time zone{" "}
              </label>
              <div className="w-full">
                <Select>
                  <SelectTrigger className="w-full h-12 rounded-xl border-0">
                    <SelectValue defaultValue={timezones[0].value} placeholder="Select timezone" />
                  </SelectTrigger>
                  <SelectContent>
                    {timezones.map(({ label, value }, i) => (
                      <SelectItem value={value}>{label}</SelectItem>
                    ))}
                  </SelectContent>
                </Select>{" "}
              </div>
            </div>
            <div className="flex items-center">
              <label htmlFor="status" className="flex items-center gap-1 w-1/5 min-w-[300px] font-medium">
                Google analytics campaign tracking
              </label>
              <div className="flex gap-3">
                <Switch defaultChecked={true} />
                <label>Enable campaign tracking if you want to see how much traffic is generated by Social Auto Poster.</label>
              </div>
            </div>
            <div className="flex items-center">
              <label htmlFor="status" className="flex items-center gap-1 w-1/5 min-w-[300px] font-medium">
                Enable social posting logs
              </label>
              <div className="flex gap-3">
                <Switch />
                <label>Enable this to store your social posting activities into the database which can be viewed from "Logs" section.</label>
              </div>
            </div>
            <div className="flex items-center">
              <label htmlFor="status" className="flex items-center gap-1 w-1/5 min-w-[300px] font-medium">
                Enable Timestamp Link
              </label>
              <div className="flex gap-3">
                <Switch />
                <label>Enable this to send timestamp with Social Link post.</label>
              </div>
            </div>
          </div>
        </div>
      </Motion>
    </Fragment>
  );
}
