import { UIcon } from "@/components/svgs/icons";
export const testimonials = [
  {
    id: 1,
    imageUrl: "/carousel/c1.svg",
    name: "Ideation and planning",
    role: "Generate and refine data-driven ideas using AI Chat and Apps, effortlessly brainstorming and creating initial drafts",
    description:
      "I've tried several website builders, but Webbuddy takes the cake. The templates are modern and customizable, and the drag-and-drop interface makes it a breeze to create a stunning website. Love it!",
  },
  {
    id: 2,
    imageUrl: "/carousel/c2.svg",
    name: "Strategy and content creation",
    role: "Develop comprehensive strategies with AI Assistants and create high-quality content with AI Article Wizard, Website, Email Builders.",
    description: "",
  },
  {
    id: 3,
    imageUrl: "/carousel/c3.svg",
    name: "Workflow automation and scheduling",
    role: "Automate tasks and streamline workflows with AI Workflows, scheduling and managing campaigns seamlessly for timely content distribution.",
    companyImage: "No doubt, Spend.In is the best!",
  },
  {
    id: 4,
    imageUrl: "/carousel/c4.svg",
    name: "Engagement and performance monitoring",
    role: "Centralize social media interactions with the Social Media Conversation Hub, monitor performance with Social Media Analytics and maintain brand reputation.",
    companyImage: "No doubt, Spend.In is the best!",
  },
  {
    id: 5,
    imageUrl: "/carousel/c5.svg",
    name: "Continuous improvement and coordination",
    role: "Refine strategies using AI Assistants, integrate processes with AI Apps, and ensure coordinated messaging and efficient data management across all platforms. ",
    companyImage: "No doubt, Spend.In is the best!",
  },
];
export const testimonialsdata = [
  {
    id: 1,
    imageUrl: "/carousel2/c1.svg",
    name: "Identify needs and plan",
    role: "Identify your needs and plan effectively with AI-driven insights and tailored solutions.",
    description:
      "I've tried several website builders, but Webbuddy takes the cake. The templates are modern and customizable, and the drag-and-drop interface makes it a breeze to create a stunning website. Love it!",
  },
  {
    id: 2,
    imageUrl: "/carousel2/c2.svg",
    name: "Create and develop content",
    role: "Create high-quality content quickly with Growstacks AI-powered tools for text and video.",
    description: "",
  },
  {
    id: 3,
    imageUrl: "/carousel2/c3.svg",
    name: "Automate marketing efforts",
    role: "Automate marketing tasks and streamline workflows for efficient and consistent operations.",
    companyImage: "No doubt, Spend.In is the best!",
  },
  {
    id: 4,
    imageUrl: "/carousel2/c4.svg",
    name: "Engage with audiences",
    role: "Enhance customer engagement and brand reach through real-time interactions and advocacy.",
    companyImage: "No doubt, Spend.In is the best!",
  },
  {
    id: 5,
    imageUrl: "/carousel2/c5.svg",
    name: "Analyze and optimize strategies",
    role: "Analyze performance and optimize strategies for better results and effective marketing.",
    companyImage: "No doubt, Spend.In is the best!",
  },
  {
    id: 6,
    imageUrl: "/carousel2/c6.svg",
    name: "Scale operations",
    role: "Scale your business with tools for customer targeting, campaign optimization, and growth strategies.",
    companyImage: "No doubt, Spend.In is the best!",
  },
];
export const testimonialsdatathirdpage = [
  {
    id: 1,
    imageUrl: "/carousel3/c1.svg",
    name: "Strategic planning and research",
    role: "Develop a clear marketing strategy and gather insights for effective execution.",
    description:
      "I've tried several website builders, but Webbuddy takes the cake. The templates are modern and customizable, and the drag-and-drop interface makes it a breeze to create a stunning website. Love it!",
  },
  {
    id: 2,
    imageUrl: "/carousel3/c2.svg",
    name: "Content creation and campaign development",
    role: "Create high-quality content and develop effective marketing campaigns.",
    description: "",
  },
  {
    id: 3,
    imageUrl: "/carousel3/c3.svg",
    name: "Content distribution and scheduling",
    role: "Distribute content effectively and manage marketing campaigns.",
    companyImage: "No doubt, Spend.In is the best!",
  },
  {
    id: 4,
    imageUrl: "/carousel3/c4.svg",
    name: "Customer engagement and support",
    role: "Engage with customers and provide effective support. ",
    companyImage: "No doubt, Spend.In is the best!",
  },
  {
    id: 5,
    imageUrl: "/carousel3/c5.svg",
    name: "Analyze and optimize strategies",
    role: "Measure performance and refine marketing strategies",
    companyImage: "No doubt, Spend.In is the best!",
  },
];
export const companyemployees = [
  {
    id: 1,
    imageUrl: "/company/1.svg",
    name: "Dianne Russell",
    role: "Senior Developer",
    imageUrlbox: "/company/1.1.svg",
  },
  {
    id: 2,
    imageUrl: "/company/2.svg",
    name: "Esther Howard",
    role: "Ux Designer",
    imageUrlbox: "/company/1.1.svg",
  },
  {
    id: 3,
    imageUrl: "/company/3.svg",
    name: "Jenny Wilson",
    role: "Front End Developer",
    imageUrlbox: "/company/1.1.svg",
  },
  {
    id: 4,
    imageUrl: "/company/4.svg",
    name: "Ralph Edwards",
    role: "Chief Executive Officer ",
    imageUrlbox: "/company/1.1.svg",
  },
  {
    id: 4,
    imageUrl: "/company/5.svg",
    name: "Ronald Richards",
    role: "Assistant Backend ",
    imageUrlbox: "/company/1.1.svg",
  },
  {
    id: 1,
    imageUrl: "/company/1.svg",
    name: "Dianne Russell",
    role: "Senior Developer",
    imageUrlbox: "/company/1.1.svg",
  },
  {
    id: 2,
    imageUrl: "/company/2.svg",
    name: "Esther Howard",
    role: "Ux Designer",
    imageUrlbox: "/company/1.1.svg",
  },
  {
    id: 3,
    imageUrl: "/company/3.svg",
    name: "Jenny Wilson",
    role: "Front End Developer",
    imageUrlbox: "/company/1.1.svg",
  },
  {
    id: 4,
    imageUrl: "/company/4.svg",
    name: "Ralph Edwards",
    role: "Chief Executive Officer ",
    imageUrlbox: "/company/1.1.svg",
  },
  {
    id: 4,
    imageUrl: "/company/5.svg",
    name: "Ronald Richards",
    role: "Assistant Backend ",
    imageUrlbox: "/company/1.1.svg",
  },
];

export const landingpage = [
  {
    id: 1,
    imageUrl: "/landingpage/l1.svg",
    name: "Overcome creative block",
    border: "#C1E0FF",
    background: "#F1F8FF",
    imageUrlbox: "/landingpage/l1.svg",
    videos: "https://growstackai.s3.amazonaws.com/QyiyJB/Box+1.mp4",
  },
  {
    id: 2,
    imageUrl: "/images_growstack/home/fBlock2.svg",
    name: "Transform ideas into content",
    border: "#FFF4BD",
    background: "#FEFAE5",
    imageUrlbox: "/landingpage/l2.svg",
    videos: "https://growstackai.s3.amazonaws.com/3LZtFl/Box+2.mp4",
  },
  {
    id: 3,
    imageUrl: "/images_growstack/home/fBlock3.svg",
    name: "Strategize with AI assistant",
    border: "#FFC3E4",
    background: "#FCF1F7",
    imageUrlbox: "/landingpage/l3.svg",
    videos: "https://growstackai.s3.amazonaws.com/dqcGLk/Box+3.mp4",
  },
  {
    id: 4,
    imageUrl: "/images_growstack/home/fBlock4.svg",
    name: "Elevate your ideas into presentable content",
    border: "#DBF8A8",
    background: "#EEF6E0",
    imageUrlbox: "/landingpage/l4.svg",
    videos: "https://growstackai.s3.amazonaws.com/nyF4Xq/Box+4.mp4",
  },
  {
    id: 5,
    imageUrl: "/images_growstack/home/fBlock5.svg",
    name: "Gather insights from your audience",
    border: "#FFE0C3",
    background: "#FFF8F6",
    imageUrlbox: "/landingpage/l5.svg",
    videos: "https://growstackai.s3.amazonaws.com/MpQYLQ/Box+5.mp4",
  },
  {
    id: 6,
    imageUrl: "/images_growstack/home/fBlock6.svg",
    border: "#C1FFC1",
    name: "Streamline your processes with AI workflow builder",
    background: "#F6FFF6",
    imageUrlbox: "/landingpage/l6.svg",
    videos: "https://growstackai.s3.amazonaws.com/pnzUIK/Box+6.mp4",
  },
  {
    id: 7,
    imageUrl: "/images_growstack/home/fBlock7.svg",
    border: "#DBBFFF",
    name: "Effortless publishing with scheduler",
    background: "#FAF6FF",
    imageUrlbox: "/landingpage/l7.svg",
    videos: "",
  },
  {
    id: 8,
    imageUrl: "/images_growstack/home/fBlock8.svg",
    border: "#FFBFBF",
    name: "Analyze your impact",
    background: "#FFF6F6",
    imageUrlbox: "/landingpage/l8.svg",
    videos: "https://growstackai.s3.amazonaws.com/TueE8F/Box%208.mp4",
  },
];

export const team = [
  {
    id: 1,
    imageUrl: "/company/a.svg",
    name: "Narasimha Rao",
    role: "CEO,    Managing Director Balvantis Studio",
    Url: "https://www.linkedin.com/in/narasimha-vadde/",
  },
  {
    id: 2,
    imageUrl: "/company/b.svg",
    name: "Nagaraj Manne",
    role: "Web Developer",
    Url: "https://www.linkedin.com/in/nagaraj-manne-17168965/",
  },
  {
    id: 3,
    imageUrl: "/company/c.svg",
    name: "Ranjit Reddy",
    role: "SAP SD/(OTC)/ Logistics S4",
    Url: "https://linkedin.com/in/ranjith-annapu-828a241a2/",
  },
  {
    id: 4,
    imageUrl: "/company/d.svg",
    name: "Anudeep Devata",
    role: "MBA, GDC, Ireland",
    Url: "https://www.linkedin.com/in/krishna-anudeep-41128b10b/",
  },
];
export const teamvideos = [
  {
    id: 1,
    videoUrl:
      "https://video.gumlet.io/673d77b6f3970d5c7faa5a64/673d9044a1954734a552e434/download.mp4",
    name: "Narasimha Rao",
    role: "CEO,    Managing Director Balvantis Studio",
    Url: "https://www.linkedin.com/in/narasimha-vadde/",
    poster: "/freelancer.png",
  },
  {
    id: 2,
    videoUrl:
      "https://video.gumlet.io/673d77b6f3970d5c7faa5a64/673d9044a1954734a552e42e/download.mp4",
    name: "Nagaraj Manne",
    role: "Web Developer",
    Url: "https://www.linkedin.com/in/nagaraj-manne-17168965/",
    poster: "/channel.png",
  },
  {
    id: 3,
    videoUrl:
      "https://video.gumlet.io/673d77b6f3970d5c7faa5a64/673d904394dde00045ea1353/download.mp4",
    name: "Ranjit Reddy",
    role: "SAP SD/(OTC)/ Logistics S4",
    Url: "https://linkedin.com/in/ranjith-annapu-828a241a2/",
    poster: "/content.png",
  },
  {
    id: 4,
    videoUrl:
      "https://video.gumlet.io/673d77b6f3970d5c7faa5a64/673d904394dde00045ea1351/download.mp4",
    name: "Anudeep Devata",
    role: "MBA, GDC, Ireland",
    Url: "https://www.linkedin.com/in/krishna-anudeep-41128b10b/",
    poster: "/gamer.png",
  },
  {
    id: 5,
    videoUrl:
      "https://video.gumlet.io/673d77b6f3970d5c7faa5a64/673d9044a1954734a552e434/download.mp4",
    name: "Narasimha Rao",
    role: "CEO,    Managing Director Balvantis Studio",
    Url: "https://www.linkedin.com/in/narasimha-vadde/",
    poster: "/freelancer.png",
  },
  {
    id: 6,
    videoUrl:
      "https://video.gumlet.io/673d77b6f3970d5c7faa5a64/673d9044a1954734a552e42e/download.mp4",
    name: "Nagaraj Manne",
    role: "Web Developer",
    Url: "https://www.linkedin.com/in/nagaraj-manne-17168965/",
    poster: "/channel.png",
  },
  {
    id: 7,
    videoUrl:
      "https://video.gumlet.io/673d77b6f3970d5c7faa5a64/673d904394dde00045ea1353/download.mp4",
    name: "Ranjit Reddy",
    role: "SAP SD/(OTC)/ Logistics S4",
    Url: "https://linkedin.com/in/ranjith-annapu-828a241a2/",
    poster: "/content.png",
  },
  {
    id: 8,
    videoUrl:
      "https://video.gumlet.io/673d77b6f3970d5c7faa5a64/673d904394dde00045ea1351/download.mp4",
    name: "Anudeep Devata",
    role: "MBA, GDC, Ireland",
    Url: "https://www.linkedin.com/in/krishna-anudeep-41128b10b/",
    poster: "/gamer.png",
  },
];
// export const solutions = [
//   {
//     id: 1,
//     imageUrl: "/solutionsicon/img1.svg",
//     name: "Large enterprises",
//     role: "   Streamline operation's with advance AI solutions",
//     bgcolor: "#e8dff5",
//     textcolor: "#034737",
//     href: "/solutions/largeenterprise",
//   },
//   {
//     id: 2,
//     imageUrl: "/solutionsicon/img2.svg",
//     name: "Mid-market",
//     role: "Conquer resources constraints with AI tools",
//     bgcolor: "#fce1e4",
//     textcolor: "#034737",
//     href: "/solutions/midmarketenterprise",
//   },

//   {
//     id: 3,
//     imageUrl: "/solutionsicon/img3.svg",
//     name: "Small businesses",
//     role: "Maximize efficiency with all-in-one AI  marketing",
//     bgcolor: "#fcf4dd",
//     textcolor: "#034737",
//     href: "/solutions/smallbusinesses",
//   },
//   {
//     id: 4,
//     imageUrl: "/solutionsicon/img4.svg",
//     name: "Startups",
//     role: "Maximize efficiency with all-in-one AI  marketing",
//     bgcolor: "#ddedea ",
//     textcolor: "#034737",
//     href: "/solutions/startup",
//   },
// ];
export const solutionsteams = [
  {
    id: 1,
    imageUrl: "/solutionsicon/img5.svg",
    name: "Marketing",
    role: "   Transform your marketing strategy with GrowStack",
    bgcolor: "#e8dff5",
    textcolor: "#034737",
    href: "/solutions/marketing",
  },
  {
    id: 2,
    imageUrl: "/solutionsicon/img6.svg",
    name: "Sales",
    role: "Transform your sales process with Growstack",
    bgcolor: "#fce1e4",
    textcolor: "#034737",
    href: "/solutions/sales",
  },
  {
    id: 3,
    imageUrl: "/solutionsicon/img7.svg",
    name: "RevOps",
    role: "Optimize your revenue strategy with  Growstack",
    bgcolor: "#fcf4dd",
    textcolor: "#034737",
    href: "/solutions/revops",
  },
  {
    id: 4,
    imageUrl: "/solutionsicon/img8.svg",
    name: "Customer service",
    role: "Elevate customer service with advanced AI solutions",
    bgcolor: "#ddedea ",
    textcolor: "#034737",
    href: "/solutions/customer_service",
  },
  {
    id: 5,
    imageUrl: "/solutionsicon/img9.svg",
    name: "Finance",
    role: "Transform finance operations with AI-Powered solutions",
    bgcolor: "#daeaf6",
    textcolor: "#034737",
    href: "/solutions/finance",
  },
  {
    id: 6,
    imageUrl: "/solutionsicon/img10.svg",
    name: "Business operations",
    role: "Streamline your business operations with Growstack",
    bgcolor: "#e8dff5",
    textcolor: "#034737",
    href: "/solutions/operations",
  },
  {
    id: 7,
    imageUrl: "/solutionsicon/img11.svg",
    name: "IT",
    role: "Transform your IT with AI - Powered solutions",
    bgcolor: "#fce1e4",
    textcolor: "#034737",
    href: "/solutions/It",
  },
  {
    id: 8,
    imageUrl: "/solutionsicon/img13.svg",
    name: "Supply chain",
    role: "Revolutionize Your Supply Chain Operations with Growstack",
    bgcolor: "#fcf4dd",
    textcolor: "#034737",
    href: "/solutions/supplychain",
  },
  {
    id: 9,
    imageUrl: "/solutionsicon/img13.svg",
    name: "Solution by Company Type",
    role: "",
    bgcolor: "#ffffff",
    textcolor: "#034737",
    href: "",
  },
  {
    id: 10,
    imageUrl: "/solutionsicon/img1.svg",
    name: "Large enterprises",
    role: "   Streamline operation's with advance AI solutions",
    bgcolor: "#e8dff5",
    textcolor: "#034737",
    href: "/solutions/largeenterprise",
  },
  {
    id: 11,
    imageUrl: "/solutionsicon/img2.svg",
    name: "Mid-market",
    role: "Conquer resources constraints with AI tools",
    bgcolor: "#fce1e4",
    textcolor: "#034737",
    href: "/solutions/midmarketenterprise",
  },

  {
    id: 12,
    imageUrl: "/solutionsicon/img3.svg",
    name: "Small businesses",
    role: "Maximize efficiency with all-in-one AI  marketing",
    bgcolor: "#fcf4dd",
    textcolor: "#034737",
    href: "/solutions/smallbusinesses",
  },
  {
    id: 13,
    imageUrl: "/solutionsicon/img4.svg",
    name: "Startups",
    role: "Supercharge growth and market penetration with integrated AI Tools",
    bgcolor: "#ddedea ",
    textcolor: "#034737",
    href: "/solutions/startup",
  },
  {
    id: 14,
    imageUrl: "/solutionsicon/img13.svg",
    name: "Solution by Teams",
    role: "",
    bgcolor: "#ffffff",
    textcolor: "#034737",
    href: "",
  },
];
