import Motion from "@/components/Motion";
import { OutputIcon2 } from "@/components/svgs";
import { Plus, Send } from "lucide-react";
import { useState } from "react";
import AddOutput from "./layout/AddOutput";
import { Fragment } from "react";
import ProvidersDrawer from "./ProvidersDrawer";
export default function OutputSection() {
  const [addNewOutput, setAddNewOutput] = useState(false);

  return (
    <Motion transition={{ duration: 0.5 }} variants={{ hidden: { opacity: 0 }, visible: { opacity: 1 } }}>
      <div className="flex items-center gap-4 border-b border-[#bbbbbb6b] border-dashed pb-8">
        <div className="bg-primary-green p-4 rounded-lg">
          <OutputIcon2 className="text-white" />
        </div>
        <div>
          <h2 className="text-xl font-medium">Output</h2>
          <span className="text-primary-black text-opacity-50 text-sm">Configure and test the output data</span>
        </div>
      </div>
      {addNewOutput ? (
        <AddOutput />
      ) : (
        <Fragment>
          <div className="mt-8 space-y-3">
            <p className="text-primary-neutral text-xl font-semibold">Get started by adding outputs or steps</p>
            <p className="text-primary-black text-opacity-70 leading-relaxed text-sm">
              Outputs will be generated by the workflow and made available to the user after execution.
            </p>
            <div className="space-y-5 !mt-8">
              <button
                onClick={() => setAddNewOutput(true)}
                className="w-full text-center bg-primary-green text-white hover:bg-primary-green/90 transition duration-500 px-5 py-4 rounded-xl flex items-center justify-center gap-2">
                <Plus size={20} />
                Add Output
              </button>
              <span className="text-center block">Or</span>
              <ProvidersDrawer
                trigger={
                  <button className="w-full text-center border border-[#E8E8E8] text-primary-green hover:bg-primary-green/10 transition duration-500 px-5 py-4 rounded-xl flex items-center justify-center gap-2">
                    <Send size={20} />
                    Publish
                  </button>
                }
              />
            </div>
          </div>
        </Fragment>
      )}
    </Motion>
  );
}
