export enum ModalContent {
  ADD_CONTACT = "ADD_CONTACT",
  DELETE_CONTACT = "DELETE_CONTACT",
  SEND_SMS = "SEND_SMS",
  CHECK_EMAIL_PERMISSION = "CHECK_EMAIL_PERMISSION",
  SEND_EMAIL = "SEND_EMAIL",
}
