name: EC2 Deployment

on:
    push:
        branches: [main]

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Install SSH key
              uses: shimataro/ssh-key-action@v2
              with:
                  key: ${{ secrets.SERVER_SSH_KEY }}
                  known_hosts: ${{ secrets.KNOWN_HOSTS }}

            - name: Deploy to EC2
              env:
                  SERVER_IP: ${{ secrets.SERVER_IP }}
                  SERVER_USER: ${{ secrets.SERVER_USER }}
                  #NEXT_PUBLIC_API_BASE_URL: ${{ secrets.NEXT_PUBLIC_API_BASE_URL }}
                  #NEXT_PUBLIC_PARAGON_PROJECT_ID: ${{ secrets.NEXT_PUBLIC_PARAGON_PROJECT_ID }}
                  #NEXT_PUBLIC_PLACES_AUTO_COMPLETE: ${{ secrets.NEXT_PUBLIC_PLACES_AUTO_COMPLETE }}
              run: |
                  ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP << EOF
                    set -e # Exit immediately if a command fails
                    cd GrowStack-Ai || exit 1
                    git fetch origin main
                    git reset --hard origin/main
                    npm install
                    npm run build
                    pm2 stop growstack || true
                    pm2 delete all
                    pm2 start npm --name growstack -- start
                    pm2 save
                    echo 'Deployment and PM2 setup with name growstack completed successfully'
                  EOF
